### ISSUE TITLE
warna has no method 'gradient'

### ISSUE THREAD

**Issue by timbowhite** [fians/warna#1]
Hi thanks for this lib.

In node.js v0.10.33, the warna.gradient example:

`var color = warna.gradient('#ffffff', '#000000').getPosition(0.5).hex;`

Fails with this:

```
var color = warna.gradient('#ffffff', '#000000').getPosition(0.5).hex;
                  ^
TypeError: Object #<Object> has no method 'gradient'
```

**Comment by fians** [comment]
Sorry, I made some typos on examples. But it has been fixed. Thanks :wink:
